SELECT 
    YEAR(D.DIFFERENTIATION_DATE) AS YEAR, 
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(D.DIFFERENTIATION_DATE))
     - D.SIZE_OF_COLONY AS YEAR_DEV,
     D.ID
FROM ECOLI_DATA D
ORDER BY YEAR, YEAR_DEV;